### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by shoc2005** [tfwu/RGM-AOGTracker#1]
Hi, compiling RGM on Ubuntu 14.04LTS I get the compilation error:

`[ 51%] Building CXX object CMakeFiles/RGM.dir/src/AOGrammar.cpp.o
In file included from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/util/UtilLog.hpp:34:0,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/common.hpp:43,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rectangle.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rgm_struct.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/feature_pyr.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/parameters.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.cpp:3:
/home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/common.hpp:270:25: warning: backslash and newline separated by space
     switch(Dimension) { \        
 ^
In file included from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rectangle.hpp:7:0,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rgm_struct.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/feature_pyr.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/parameters.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.cpp:3:
/home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/common.hpp:270:25: warning: backslash and newline separated by space
     switch(Dimension) { \        
 ^
In file included from /usr/local/include/boost/archive/detail/interface_iarchive.hpp:22:0,
                 from /usr/local/include/boost/archive/detail/common_iarchive.hpp:23,
                 from /usr/local/include/boost/archive/basic_binary_iarchive.hpp:30,
                 from /usr/local/include/boost/archive/binary_iarchive_impl.hpp:21,
                 from /usr/local/include/boost/archive/binary_iarchive.hpp:20,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/common.hpp:9,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rectangle.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rgm_struct.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/feature_pyr.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/parameters.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.cpp:3:
/usr/local/include/boost/archive/detail/iserializer.hpp: In instantiation of ‘static void boost::archive::detail::heap_allocation<T>::has_new_operator::invoke_delete(T*) [with T = RGM::Scaleprior]’:
/usr/local/include/boost/archive/detail/iserializer.hpp:264:35:   required from ‘static void boost::archive::detail::heap_allocation<T>::invoke_delete(T*) [with T = RGM::Scaleprior]’
/usr/local/include/boost/archive/detail/iserializer.hpp:272:30:   required from ‘boost::archive::detail::heap_allocation<T>::~heap_allocation() [with T = RGM::Scaleprior]’
/usr/local/include/boost/archive/detail/iserializer.hpp:293:36:   required from ‘void* boost::archive::detail::pointer_iserializer<Archive, T>::heap_allocation() const [with Archive = boost::archive::text_iarchive; T = RGM::Scaleprior]’
/home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.cpp:3972:1:   required from here
/usr/local/include/boost/archive/detail/iserializer.hpp:236:47: error: invalid conversion from ‘long unsigned int’ to ‘void*’ [-fpermissive]
                 (T::operator delete)(t, sizeof(T));
                                               ^
In file included from /usr/include/eigen3/Eigen/Core:256:0,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/common.hpp:38,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rectangle.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rgm_struct.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/feature_pyr.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/parameters.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.cpp:3:
/usr/include/eigen3/Eigen/src/Core/util/Memory.h:637:12: note: initializing argument 2 of ‘static void RGM::Scaleprior::operator delete(void*, void*)’
       void operator delete(void * memory, void *ptr) throw() { return ::operator delete(memory,ptr); } \
            ^
/usr/include/eigen3/Eigen/src/Core/util/Memory.h:648:41: note: in expansion of macro ‘EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF’
 #define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                         ^
/home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/parameters.hpp:176:5: note: in expansion of macro ‘EIGEN_MAKE_ALIGNED_OPERATOR_NEW’
     EIGEN_MAKE_ALIGNED_OPERATOR_NEW;
     ^
In file included from /usr/local/include/boost/archive/detail/interface_iarchive.hpp:22:0,
                 from /usr/local/include/boost/archive/detail/common_iarchive.hpp:23,
                 from /usr/local/include/boost/archive/basic_binary_iarchive.hpp:30,
                 from /usr/local/include/boost/archive/binary_iarchive_impl.hpp:21,
                 from /usr/local/include/boost/archive/binary_iarchive.hpp:20,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/common.hpp:9,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rectangle.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rgm_struct.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/feature_pyr.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/parameters.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.cpp:3:
/usr/local/include/boost/archive/detail/iserializer.hpp: In instantiation of ‘static void boost::archive::detail::heap_allocation<T>::has_new_operator::invoke_delete(T*) [with T = RGM::Deformation]’:
/usr/local/include/boost/archive/detail/iserializer.hpp:264:35:   required from ‘static void boost::archive::detail::heap_allocation<T>::invoke_delete(T*) [with T = RGM::Deformation]’
/usr/local/include/boost/archive/detail/iserializer.hpp:272:30:   required from ‘boost::archive::detail::heap_allocation<T>::~heap_allocation() [with T = RGM::Deformation]’
/usr/local/include/boost/archive/detail/iserializer.hpp:293:36:   required from ‘void* boost::archive::detail::pointer_iserializer<Archive, T>::heap_allocation() const [with Archive = boost::archive::text_iarchive; T = RGM::Deformation]’
/home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.cpp:3972:1:   required from here
/usr/local/include/boost/archive/detail/iserializer.hpp:236:47: error: invalid conversion from ‘long unsigned int’ to ‘void*’ [-fpermissive]
                 (T::operator delete)(t, sizeof(T));
                                               ^
In file included from /usr/include/eigen3/Eigen/Core:256:0,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/common.hpp:38,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rectangle.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/rgm_struct.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/feature_pyr.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/parameters.hpp:4,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.hpp:7,
                 from /home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/AOGrammar.cpp:3:
/usr/include/eigen3/Eigen/src/Core/util/Memory.h:637:12: note: initializing argument 2 of ‘static void RGM::Deformation::operator delete(void*, void*)’
       void operator delete(void * memory, void *ptr) throw() { return ::operator delete(memory,ptr); } \
            ^
/usr/include/eigen3/Eigen/src/Core/util/Memory.h:648:41: note: in expansion of macro ‘EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF’
 #define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                         ^
/home/sholc/Documents/AirDog/object_tracking/source/RGM-AOGTracker/src/parameters.hpp:232:5: note: in expansion of macro ‘EIGEN_MAKE_ALIGNED_OPERATOR_NEW’
     EIGEN_MAKE_ALIGNED_OPERATOR_NEW
     ^
make[2]: *** [CMakeFiles/RGM.dir/src/AOGrammar.cpp.o] Error 1
make[1]: *** [CMakeFiles/RGM.dir/all] Error 2
make: *** [all] Error 2
`

So all dependences are satisfied.

**Comment by tfwu** [comment]
Looks like it is caused by c++ boost. What version of boost are you using?  I tested the code using 1.55 and 1.60. If it is ok, please switch to 1.55 for the best practice. thanks

**Comment by shoc2005** [comment]
Exactly problem caused by Boost version 1.59. Problem solved with 1.55 version. Thanks!
